name: 🥳 New Poc List

on:
  push:
    branches:
      - main
  schedule:
    #  every day at 5:30 
      - cron:  '30 1 * * *'
  
  workflow_dispatch:
  
jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Search GitHub
        run: |
          query="top poc list"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/search/repositories?q=$query" \
               | jq .items[].html_url \
               | tee search_results.txt

      - name: Update README
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const results = fs.readFileSync('search_results.txt', 'utf-8')
            const readme = fs.readFileSync('README.md', 'utf-8')
            const newReadme = readme.replace(/<!--START_SECTION:top-poc-list-->[\s\S]*<!--END_SECTION:top-poc-list-->/, `<!--START_SECTION:top-poc-list-->\n${results}\n<!--END_SECTION:top-poc-list-->`)
            fs.writeFileSync('README.md', newReadme)
